services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPEN_WEBUI_PORT:-3000}:8080"
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:${OLLAMA_PORT:-11434}'
    extra_hosts:
      - "host.docker.internal:host-gateway"