#!/bin/bash
# Generated by opencode: src/test-mocks.sh
# Contains mock functions to stub out external dependencies for reliable unit testing.
# These mocks simulate OS calls (systemctl, curl) and external services.

# --- Mocking Systemctl/Systemd ---

# Mock: systemctl is-active
# This mock checks a global mock state variable to determine the "active" state.
mock_systemctl_is_active() {
    local service_name="$1"
    case "$service_name" in
        "ollama.service")
            # By default, assume the service is active for tests that don't change it.
            # The test script should change this mock state if needed.
            if [[ "$MOCK_OLLAMA_ACTIVE" == "true" ]]; then return 0; else return 1; fi
            ;;
        *)
            # Assume unknown
            return 1
            ;;
    esac
}

# Mock: Check if systemd is running
mock_is_systemd_system() {
    # Assume systemd is always running when running tests, unless explicitly mocked.
    if [[ "$MOCK_IS_SYSTEMD" == "false" ]]; then return 1; else return 0; fi
}

# Mock: systemctl cat
mock_systemctl_cat() {
    local service_name="$1"
    if [[ "$service_name" == "ollama.service" ]]; then
        # Simulate a successful cat output if the service is found.
        echo "Loaded: loaded (/etc/systemd/system/ollama.service; static)"
    else
        return 1 # Return failure if service is not found
    fi
}

# Mock: systemctl start
# Returns 0 if the service is mocked to be active now.
mock_systemctl_start() {
    local service_name="$1"
    if [[ "$service_name" == "ollama.service" ]]; then
        echo "Mock: Started $service_name" >&2
        export MOCK_OLLAMA_ACTIVE="true"
        return 0
    fi
    return 1
}

# Mock: systemctl stop (optional)
mock_systemctl_stop() {
    local service_name="$1"
    if [[ "$service_name" == "ollama.service" ]]; then
        echo "Mock: Stopped $service_name" >&2
        export MOCK_OLLAMA_ACTIVE="false"
        return 0
    fi
    return 1
}

# Mock: systemctl daemon-reload
mock_systemctl_daemon_reload() {
    echo "Mock: Daemon reloaded successfully."
    return 0
}

# Mock: systemctl restart
mock_systemctl_restart() {
    local service_name="$1"
    echo "Mock: $service_name restarted successfully."
    return 0
}

# --- Mocking Curl/CURL ---
# Global variable to control curl's success/failure
MOCK_CURL_SUCCESS=true

# Overrides the actual curl command.
# Processes arguments to check for --silent and exit code simulation.
mock_curl_call() {
    local first_arg="$1"
    shift
    
    if ! $MOCK_CURL_SUCCESS; then
        return 1 # Simulate failure
    fi
    
    # Simple pattern matching for common check calls
    if [[ "$first_arg" == "--fail" && "$*" =~ "http://localhost:11434" ]]; then
        # Simulate a successful connection, but since we are mocking the whole
        # command, we will rely on the exit code return value.
        echo "Mock: Connection succeeded." >&2
        return 0
    fi
    
    # For successful data fetching, mock some example JSON output
    if [[ "$first_arg" == "--silent" && "$*" =~ "/api/tags" ]]; then
        echo '{
            "models": [
                {"name": "llama3", "size": 4718000000, "modified_at": "2024-09-01T12:00:00Z"},
                {"name": "mistral", "size": 4280000000, "modified_at": "2024-08-15T10:00:00Z"}
            ]
        }'
        return 0
    fi
    
    echo "Mock curl executed." >&2
    return 0
}

# --- Mocking OpenWebUI ---
# Mock run_webui_compose to always succeed for testing flow control.
run_webui_compose() {
    echo "Mock: Listing webui containers (Success)"
    return 0
}

# --- Mocking Ollama CLI ---

# Overrides the ollama command
# Simulates success (return 0) for pull, rm, etc., unless mocked otherwise.
ollama() {
    local command="$1"
    local model_name="$2"
    
    if [[ "$command" == "pull" ]]; then
        echo "Mock: Starting pull for $model_name" >&2
        return 0
    elif [[ "$command" == "rm" ]]; then
        echo "Mock: Removing $model_name" >&2
        return 0
    fi
    # Default success
    return 0
}

# --- Mocking Utilities ---
# Replaces the actual command with the mock
_check_command_exists() {
    local cmd="$1"
    case "$cmd" in
        "systemctl") return 0 ;;
        "curl") return 0 ;;
        "ollama") return 0 ;;
        "jq") return 0 ;;
        *) return 1 ;;
    esac
}

# Set these global variables in the calling test script to control mock behavior
# export MOCK_OLLAMA_ACTIVE="true"
# export MOCK_IS_SYSTEMD="true"
# export MOCK_CURL_SUCCESS="true"